version: "3.9"

services:
  users-service:
    build: .
    container_name: users-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MONGODB_URI=${MONGODB_URI:-mongodb://localhost:27017/users-management-db}
      - MONGODB_DATABASE=users-management-db
    networks:
      - eciexpress-network

networks:
  eciexpress-network:
    driver: bridge